# Use postgres/mysecretpassword as user/password credentials
version: '2.4'
services:
  postgis:
    image: tobi312/rpi-postgresql-postgis:TAG
    container_name: postgis
    volumes:
      - ./postgis:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
       POSTGRES_PASSWORD: mysecretpassword
       #POSTGRES_DB: user
       #POSTGRES_USER: user
       #PGDATA: /var/lib/postgresql/data/pgdata
    restart: unless-stopped
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      #start_period: 60s
      interval: 30s
      timeout: 5s
      retries: 5